spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/StreamFlix
spring.datasource.username=test
spring.datasource.password=123456

# Tells Java which specific database driver class to use
spring.datasource.driver-class-name=org.postgresql.Driver

# Tells Spring to automatically run your schema.sql and data.sql files on startup
spring.sql.init.mode=always

spring.sql.init.schema-locations=classpath:sql/schema/*.sql
spring.sql.init.data-locations=classpath:sql/data/*.sql
