services:
    postgres:
        image: postgres:16
        container_name: posty
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: test
        ports:
            - "5432:5432"
        tmpfs:
            - /var/lib/postgresql/data

        volumes:
            - ./src/main/resources/sql/db_init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test -d StreamFlix"]
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build: .
        container_name: demo-app
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/StreamFlix
        ports:
            - "8080:8080"
